---

- name: Install flirc_usb dependencies
  ansible.builtin.apt:
    name:
      - libhidapi-hidraw0
      - libreadline8
      - python3-setuptools
      - python3-pip
      - python3-apt

- name: Fix a symlink libreadline.so.6 to libreadline.so.8
  ansible.builtin.file:
    state: link
    src: /usr/lib/arm-linux-gnueabihf/libreadline.so.8
    dest: /usr/lib/arm-linux-gnueabihf/libreadline.so.6
    owner: root
    group: root

- name: Fetch latest flirc_util package from internet
  register: flirc_package
  ansible.builtin.get_url:
    url: http://apt.flirc.tv/arch/armhf/flirc.latest.armhf.tar.gz
    dest: /tmp

- name: Unpack Flirc package
  ansible.builtin.unarchive:
    remote_src: yes
    src: /tmp/flirc.latest.armhf.tar.gz
    dest: /tmp

- name: Copy the binary in place
  ansible.builtin.copy:
    remote_src: yes
    src: /tmp/Flirc/flirc_util
    dest: /usr/local/bin
    mode: "0755"
    owner: root
    group: root

- name: Flirc, verify util
  shell: flirc_util version
  changed_when: False

- name: Cleanup left-overs
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - /tmp/Flirc/
    - /tmp/flirc.latest.armhf.tar.gz
